version: '3.8'

services:
  jim-jam-url-shortener-service:
    build: .
    ports:
      - "8081:8080"
    environment:
      - KEY_GENERATION_SERVICE_URL=key-generation-service
      - DOMAIN=http://localhost:8081
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/mappedKeys
    depends_on:
      - key-generation-service

  key-generation-service:
    image: key-generation-service:latest
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/keys
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: